# Generated by Django 4.0.5 on 2022-06-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_im4',
            new_name='product_img4',
        ),
    ]
