# Generated by Django 4.0.5 on 2022-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customeraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='size',
        ),
        migrations.AddField(
            model_name='carts',
            name='sizeofproduct',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='Select', max_length=5),
        ),
    ]
