# Generated by Django 4.0.5 on 2022-06-30 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_size_carts_sizeofproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('lookbook', 'lookbook'), ('slider', 'slider')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='number',
            field=models.IntegerField(),
        ),
    ]
