# Generated by Django 4.0.5 on 2022-07-04 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_products_category_alter_customeraddress_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='dob',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img1',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img2',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img3',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img4',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
        migrations.CreateModel(
            name='Orderplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('packed', 'packed'), ('delivered', 'delivered')], default='pending', max_length=50)),
                ('Customeraddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customeraddress')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
