# Generated by Django 4.0.6 on 2022-07-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_customeraddress_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplace',
            name='sizeofproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.carts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carts',
            name='sizeofproduct',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=5),
        ),
    ]
