# Generated by Django 4.0.6 on 2022-07-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderplace_sizeofproduct_alter_carts_sizeofproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplace',
            name='sizeofproduct',
        ),
    ]
