# Generated by Django 4.0.6 on 2022-07-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_orderplace_sizeofproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplace',
            name='sizeofproduct',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.carts'),
            preserve_default=False,
        ),
    ]
