# Generated by Django 4.0.6 on 2022-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_orderplace_sizeofproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplace',
            name='sizeofproduct',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
